### ISSUE TITLE
Replace deprecated gateway4 by routes

### ISSUE THREAD

**Issue by tobiashuste** [hifis-net/ansible-role-netplan#77]
`gateway4`  is deprected and should be replaced by `routes` instead.

```
gateway4: "192.168.10.1"
```

needs to be converted to

```yaml
routes:
  - to: default
    via: "192.168.10.1"
```
